# fly.toml app configuration file for mock-hydro-power

app = "mock-hydro-power"
primary_region = "arn"

[build]

[http_service]
  internal_port = 4010 # Change this to match the port exposed by Prism
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "4010" # Explicitly set the PORT environment variable for the container

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 0.25
  memory_mb = 512